excluded:
  - .build

disabled_rules:
  - trailing_comma # Handled by SwiftFormat

opt_in_rules:
  # Performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_count
  - first_where
  - last_where
  - sorted_first_last
  - reduce_into

  # Code Quality
  - force_unwrapping
  - identical_operands
  - yoda_condition
  - overridden_super_call

  # Modern Swift
  - shorthand_optional_binding
  - implicit_return
  - toggle_bool
  - legacy_multiple

  # Style
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
