name: Build check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    outputs:
      should-build: ${{ steps.filter.outputs.build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Detect relevant changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            build:
              - "**/*.swift"
              - "**/*.nix"
              - "**/flake.nix"
              - "**/flake.lock"
              - "**/Package.swift"
              - "**/Package.resolved"

  build:
    name: Build (${{ matrix.system }})
    # DeterminateNix does not support x86_64-darwin natively.
    # Use aarch64-darwin runner with Rosetta 2 to build for x86_64-darwin.
    runs-on: macos-15
    needs: detect-changes
    if: >-
      needs.detect-changes.outputs.should-build == 'true' ||
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-darwin
          - x86_64-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@92ffb5400c3776307a27a1727d7e2ac3dcd9f844 # v3.18.1
        with:
          extra-conf: |
            extra-substituters = https://nix-cache.cffnpwr.dev
            extra-trusted-public-keys = cffnpwr-nixpkgs-extras:dmp2DUGwdqawLCPOsOcRxU/NpCO/qA1jha/8rmoSzvA=

      - name: Build
        run: nix build --print-build-logs --system ${{ matrix.system }}
