name: Update swiftpm2nix generated files

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Package.swift"
      - "**/Package.resolved"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-swiftpm2nix:
    name: Update swiftpm2nix generated files
    runs-on: macos-15
    if: contains(github.event.pull_request.labels.*.name, 'renovate')
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.UPDATE_APP_ID }}
          private-key: ${{ secrets.UPDATE_PRIVATE_KEY }}
          permission-contents: write

      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@32cb6a5ae30bb0dfc996fa7baf8bf1ed28442fa4 # v3.17.3
        with:
          extra-conf: |
            extra-substituters = https://nix-cache.cffnpwr.dev
            extra-trusted-public-keys = cffnpwr-nixpkgs-extras:dmp2DUGwdqawLCPOsOcRxU/NpCO/qA1jha/8rmoSzvA=\

      - name: Install dependencies
        run: nix develop --command swift package resolve

      - name: Update swiftpm2nix generated files
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
          USER_ID: ${{ steps.get-user-id.outputs.user-id }}
        run: |-
          git remote set-url origin "https://x-access-token:${APP_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "$GITHUB_HEAD_REF"
          git checkout -B "$GITHUB_HEAD_REF" "${{ github.event.pull_request.head.sha }}"

          nix develop --command swiftpm2nix
          mv nix/default.nix nix/darwin-ism/generated/default.nix
          mv nix/workspace-state.json nix/darwin-ism/generated/workspace-state.json

          if ! git diff --quiet nix/darwin-ism/generated/; then
            git config user.name "${APP_SLUG}[bot]"
            git config user.email "${USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
            git add nix/darwin-ism/generated/
            git commit -m "fix(nix): :package: update swiftpm2nix generated files"
            git push origin "$GITHUB_HEAD_REF"
          fi
